spring.application.name=helpdesk


spring.ai.openai.api-key = lm-studio
spring.ai.openai.base-url = http://127.0.0.1:1234/v1
spring.ai.openai.chat.options.model = qwen/qwen2.5-coder-7b-instruct
spring.ai.openai.chat.options.max-tokens=2048
spring.ai.openai.timeout=300s
spring.ai.openai.embedding.options.encoding-format=float


spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update


spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.max-document-batch-size=10000


app.weather.api-key = 0ae0bf475edb46c0903113933260806